### ISSUE TITLE
Specify YouTube source

### ISSUE THREAD

**Issue by tylerrbeauregard** [cooperhammond/irs#45]
Is there a way to add a specific YouTube url for download with a Spotify song or album instead of hoping that the selection algorithm gets it right? It works well most of the time, but occasionally, it has downloaded and converted a video of the entire album multiple times over, which is tedious to fix manually.

**Comment by Mhowser** [comment]
I second this, sometimes when I get a song I hear some cheesy remix instead.

**Comment by Who23** [comment]
Looking through the source it seems like a pretty simple feature to add for individual songs and playlists from youtube. 

Albums are a lot trickier though - how does the user provide the links to only some songs? how do they know which songs? how do they know how many songs? Maybe you could specify user input to skip/provide a URL while downloading the songs, but I think that deserves it's own PR.

I think I can do this pretty easily for songs and playlists though, and I'll send a PR for those in the next two weeks.

**Comment by Who23** [comment]
I was just looking through the code again and I misunderstood the playlist type - I thought it was a youtube playlist not a spotify one.

Since that's the case I'll try to work the solution for the album/playlists in the same PR
