### ISSUE TITLE
Downloading only metadata

### ISSUE THREAD

**Issue by bizzlerulez** [cooperhammond/irs#50]
Hey is it possible to download only metadata without downloading the song?

**Comment by cooperhammond** [comment]
Sorry about this, I've been working on a crystal port for the past 6 months in between school and other personal projects, and as such I'm not really supporting the python build anymore. It was a cluster fuck of code that was taking far too much time to actively maintain.

I'd highly recommend checking out the new version on Windows Subsystem for Linux, but there was so much disparity between systems on the python version that I gave up on it.
