### ISSUE TITLE
FEATURE REQUEST: option to apply metadata to local / already downloaded file

### ISSUE THREAD

**Issue by Mhowser** [cooperhammond/irs#53]
Lets say you already have some songs on disk, but no metadata for them, it would be great if IRS could have an option in the menu to add the metadata to said music files.

related to #50

**Comment by cooperhammond** [comment]
The insanity that 3 years later this request gets closed, I can't believe this project is still garnering interest.

**Comment by WSINTRA** [comment]
> The insanity that 3 years later this request gets closed, I can't believe this project is still garnering interest.

Its a good project thats why 😃
