### ISSUE TITLE
Keep getting error while doing irs --setup

### ISSUE THREAD

**Issue by amit-bhandari** [cooperhammond/irs#57]
Tried in both Linux and Windows.
Tried in both python2 and python3 

`Traceback (most recent call last):                                                                                        File "C:\Users\AB\AppData\Local\Programs\Python\Python37\Scripts\irs-script.py", line 11, in <module>                     load_entry_point('irs==7.0.2', 'console_scripts', 'irs')()                                                            File "c:\users\ab\appdata\local\programs\python\python37\lib\site-packages\irs\cli\cli.py", line 40, in main              set_it_up()                                                                                                           File "c:\users\ab\appdata\local\programs\python\python37\lib\site-packages\irs\install\setup.py", line 13, in set_it_up                                                                                                                           bin_path = os.path.join(conf_path, "bin")                                                                             File "c:\users\ab\appdata\local\programs\python\python37\lib\ntpath.py", line 76, in join                                 path = os.fspath(path)                                                                                              TypeError: expected str, bytes or os.PathLike object, not NoneType     `

**Comment by palmenros** [comment]
I also have found this error. Have you find a workaround?

**Comment by amit-bhandari** [comment]
No

**Comment by NightMachinary** [comment]
Ubuntu 18, Python 3.7.3
```
irs --setup
Traceback (most recent call last):
  File "/home/mary/miniconda3/bin/irs", line 10, in <module>
    sys.exit(main())
  File "/home/mary/miniconda3/lib/python3.7/site-packages/irs/cli/cli.py", line 40, in main
    set_it_up()
  File "/home/mary/miniconda3/lib/python3.7/site-packages/irs/install/setup.py", line 13, in set_it_up
    bin_path = os.path.join(conf_path, "bin")
  File "/home/mary/miniconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
                                                                    
```

**Comment by NightMachinary** [comment]
I found this alternative, https://github.com/ritiek/spotify-downloader.
Works great.

**Comment by dylanbaxter** [comment]
I was able to resolve this issue...

The **set_it_up** function in setup.py, line 13 references **conf_path**, which is None because the installation evidently did not set the **irs_config_dir** environment variable. The previous line in setup.py attempts to locate this environment variable, which should resemble _[HOMEDIR]/.irs_.

So I ran the following (on Ubuntu):
> export irs_config_dir=/home/dylan/.irs

I also added the line to /home/dylan/.bash_profile in order to persist the setting after restarts...

For Winders:
> setx irs_config_dir "%HOMEPATH%\\.irs"

You will have to close and reopen the command prompt for the variable to take effect...

'Hope that helps!

**Comment by Mhowser** [comment]
This is great! Can you fix this as a PR?

**Comment by cooperhammond** [comment]
Sorry about this, I've been working on a crystal port for the past 6 months in between school and other personal projects, and as such I'm not really supporting the python build anymore. It was a cluster fuck of code that was taking far too much time to actively maintain.

I'd highly recommend checking out the new version on Windows Subsystem for Linux, but there was so much disparity between systems on the python version that I gave up on it.

**Comment by Mhowser** [comment]
Hey, glad to see you back on this project! This crystal port sounds
exciting, do you have a link to it?
