### ISSUE TITLE
There's no config set up. Set up a configuration folder by running `irs --setup`

### ISSUE THREAD

**Issue by derpyranbowpop** [cooperhammond/irs#59]
hi i am using windows 10 python 3.8.2 Just finnished setting up and im getting the error above saying the .irs config folder isn't there runing "irs -- setup" creates the folders with 2 .exe files in .bin and a config.yml i will attach screenshots of both the error and the .irs folder

Error
![Capture](https://user-images.githubusercontent.com/55472010/81371603-a2e16580-913b-11ea-985e-6b7221e7ee89.PNG)
.irs Folder
![Capture](https://user-images.githubusercontent.com/55472010/81371739-04093900-913c-11ea-9ee8-4adcfbe4ea74.PNG)
bin Folder in .irs Folder
![Capture](https://user-images.githubusercontent.com/55472010/81371811-31ee7d80-913c-11ea-956a-be88f9b971a9.PNG)

**Comment by cooperhammond** [comment]
Sorry about this, I've been working on a crystal port for the past 6 months in between school and other personal projects, and as such I'm not really supporting the python build anymore. It was a cluster fuck of code that was taking far too much time to actively maintain.

I'd highly recommend checking out the new version on Windows Subsystem for Linux, but there was so much disparity between systems on the python version that I gave up on it.
