### ISSUE TITLE
Program hangs on download

### ISSUE THREAD

**Issue by bogga** [cooperhammond/irs#65]
I'm running this via source (i.e. cloning, compiling). I've copied irs to my home directory for convenience, in case that matters. Behaviour is the same running from home or cd'ing into repo/bin/ and running from the binary there.

When I run irs to get a song or an album, it successfully gets to "Downloading video" and then appears to completely hang, like this:
```
./irs --song "Bohemian Rhapsody" --artist "Queen"
[Bohemian Rhapsody by Queen]
  + Metadata found
  + URL found
  Downloading video:
```
(for an album:)
```
./irs --album "On Air" --artist "Queen"
+ On Air by Queen
[1/24]
[My Fairy King - BBC Session / February 5th 1973, Langham 1 Studio by Queen]
  + URL found
  Downloading video:
```

I left it for 15 minutes just in case, but it stayed hanging at that point.

**Comment by bogga** [comment]
More info: when I run `./irs --install` I chose Linux as my option (I run WSL2), not sure if this is the correct choice. I installed again and chose Windows - still no luck.

**Comment by bogga** [comment]
After installing `youtube-dl` and `python-as-python3` (via apt-get) it works!

**Comment by cooperhammond** [comment]
Good to hear! I think that there is something wrong with the youtube-dl binary that needs python as a dependency when it shouldn't because I had a similar problem.
