### ISSUE TITLE
Cant get past irs --install

### ISSUE THREAD

**Issue by Mhowser** [cooperhammond/irs#67]
I compiled `irs` following the directions, I made the config.yml file, and I set the `IRS_CONFIG_LOCATION` variable. But I cant get past This warning message.
![image](https://user-images.githubusercontent.com/24195572/92442752-45027000-f165-11ea-952c-477524165866.png)
Any ideas?

**Comment by Who23** [comment]
- restart your session, check if IRS_CONFIG_LOCATION is still set
- make IRS_CONFIG_LOCATION an absolute path
- Make sure it's pointing at the config.yml

Can you echo `IRS_CONFIG_LOCATION`?

**Comment by Mhowser** [comment]
I fixed it by putting `export IRS_CONFIG_LOCATION=/full/path/to/config.yml` in my `.bashrc`. Thank you for the help!
