### ISSUE TITLE
Unhandled exception: Index out of bounds (IndexError)

### ISSUE THREAD

**Issue by Mhowser** [cooperhammond/irs#68]
I was trying to download a song by specifying the URL and this happened 
![image](https://user-images.githubusercontent.com/24195572/92691251-27651000-f2f7-11ea-9ced-7d999c2a3ec3.png)

**Comment by Who23** [comment]
Does it still crash with an index error when you aren't specifiying a URL?

**Comment by Mhowser** [comment]
same crash 
![image](https://user-images.githubusercontent.com/24195572/92847572-25a25780-f39e-11ea-8a3a-b3ff6c424653.png)

**Comment by Mhowser** [comment]
Oh I forgot to mention I am using the latest crystal version on Ubuntu 18.04

**Comment by Who23** [comment]
Yup this is definitely a problem with assuming each artist has at least one tagged genre. The spotify API says that artists may not have any genres tagged to them.
