### ISSUE TITLE
Youtube organization changed

### ISSUE THREAD

**Issue by NightMean** [cooperhammond/irs#75]
Hi,
I tried to use your app for the first time using the latest prebuilt binary but when I try to download some song I'm prompted with this error. Should I compile latest IRS to fix this?

Traceback: 
```console
michal@Michal-PC:~/Downloads/IRS$ ./irs --artist "Alynda Segarra" --song "Drunken Angel"
[Drunken Angel by Alynda Segarra]
  + Metadata found
Youtube has changed the way it organizes its webpage, submit a bug
on https://github.com/cooperhammond/irs
```

**Comment by cooperhammond** [comment]
Hey, give the newest release [here](https://github.com/cooperhammond/irs/releases/tag/1.2.1) a try! I haven't pushed out a binary in awhile, thanks for bringing this up.

**Comment by NightMean** [comment]
Thank you! Works as expected! :)

**Comment by cooperhammond** [comment]
Glad to hear it!
