### ISSUE TITLE
Feature: Allow selecting youtubevideo to download

### ISSUE THREAD

**Issue by JonnyCodewalker** [cooperhammond/irs#76]
Right now irs downloads the video it deems most suitable whenever the user does not specify a specific URL. Sometimes this results in bad videos being selected. Most of the time this happended to me it would have been easy for me to see if the program had output the title/length of the video. 

Not sure how feasable this is, but after getting the request and ranking them, it might be a nice idea to output the top X videos (name, length, maybe channel?) and ask the user to pick the one he wants to proceed with. 

Probably behind a new flag, as to stay backwards compatible. 

----
Alternatively, if the process should stay noninteractive. It might be a good idea to look at the average length of the top X picks and only select the top one if it is not siginficantly longer/shorter than the rest.

**Comment by bogga** [comment]
Might get better accuracy to grab the song length from the spotify API & then go down each video on YT, finding the result with the closest length to what spotify says

**Comment by cooperhammond** [comment]
Some interesting ideas here, I'll try to get a mockup going tonight!

**Comment by cooperhammond** [comment]
Both of these requests should be met with #77 and #78

**Comment by JonnyCodewalker** [comment]
@cooperhammond Hey, it seems like you updated internally to 1.4.0, but you did not publish a release.
Besides that, having looked over the code it seems like a reasonable implementation, even though I am not that familiar with Crystal. :+1:
