### ISSUE TITLE
Can't find libevent-2.1.so.6

### ISSUE THREAD

**Issue by daraul** [cooperhammond/irs#80]
When I try to install irs, I get `error while loading shared libraries: libevent-2.1.so.6`. I realize this is an issue on my OS (popos), but maybe there's some package I should be installing? 

I tried searching the ubuntu repos for the file, but no luck.

https://packages.ubuntu.com/search?searchon=contents&keywords=libevent-2.1.so.6&mode=exactfilename&suite=hirsute&arch=any

**Comment by cooperhammond** [comment]
Hmm, this is interesting, are you building from source?

**Comment by daraul** [comment]
Nope, I just download the [latest release](https://github.com/cooperhammond/irs/releases/download/1.2.1/linux64_86_v1.2.1.zip), unzip it, symlink the irs binary to ~/.local/bin, and try to run it.

**Comment by cooperhammond** [comment]
Try to give the newest release a try, I'm not expecting it to fix much, but maybe...

**Comment by daraul** [comment]
That doesn't do it, but maybe I've misconfigured the "binary_directory" variable. I just realized I had it set to "~/.irs/bin", when I was dropping the binary into "~/.local/bin". Do you think that might be it?

**Comment by cooperhammond** [comment]
That's certainly a problem, but it shouldn't be giving you an error like that. I believe there's some form of catch that would tell you whether you had your config misconfigured. 

https://stackoverflow.com/questions/17110844/error-while-loading-shared-libraries-libevent-1-4-so-2-cannot-open-shared-obje

https://pkgs.org/download/libevent-2.1.so.6()(64bit)

https://www.programmersought.com/article/54035038658/

These are some links I found, hopefully, they can help. Most pertinent seems to be the last one, but give them all a look and see if they can help you out.

**Comment by cooperhammond** [comment]
Any luck fixing it?

**Comment by daraul** [comment]
Haven't made another attempt at it yet. When I do I'll drop you a line here.

**Comment by daraul** [comment]
This just gets weirder and weirder. I installed memcached on my arch machine, which replaced this error with `error while loading shared libraries: libpcre.so.3`. So now it can't find that. I installed memcached on my popos machine, and that did nothing to fix the error. I'll try just downloading the libraries and symlinking them to the appropriate place and get back to you.

**Comment by daraul** [comment]
Wait, my mistake. I just uninstalled memcached and arch still complained about libpcre.so.3, so it seems like installing memcached didn't do anything there either.

**Comment by daraul** [comment]
Right, I downloaded the `deb` file from [here](https://debian.pkgs.org/sid/debian-main-amd64/libevent-2.1-6_2.1.8-stable-4_amd64.deb.html), and installed it. That works on my popos machine. 

It doesn't seem like this is expected to happen, though. So, did I do something wrong?

**Comment by cooperhammond** [comment]
Wait, so just to be clear it is running now? I don't think you did anything wrong, I think it's probably just some form of environment error/misconfig.

 Also, it might be worth testing whether any other Crystal lang binaries will run on your machine because I'm doubtful it's a problem unique to the binaries this project produces.

**Comment by daraul** [comment]
Yes, it works on popos. I figured it might be an OS specific issue, but i
wasn't sure where else to start looking for solutions. I don't know of any
other crystal projects, I think this might be the first I've encountered.

**Comment by cooperhammond** [comment]
Yeah Crystal is a bit obscure still and I don't know about popos so it might be in the same boat, bad luck I guess :/ Glad you got it working!
