### ISSUE TITLE
Youtube layout changed error

### ISSUE THREAD

**Issue by JonnyCodewalker** [cooperhammond/irs#81]
IRS is currently unusable, seems like youtube had internal changes again.

**Comment by cooperhammond** [comment]
Hmm, I just ran IRS fine, what version are you using?

**Comment by cooperhammond** [comment]
Did you try `irs --install`? Your `youtube-dl` binary might be out of date.

**Comment by cooperhammond** [comment]
I'm going to shut this as no one else has run into this error.
