### ISSUE TITLE
Install Struggle

### ISSUE THREAD

**Issue by photographer2010** [cooperhammond/irs#88]
Hello there, I am a new user and I am having issues to install this. Can someone send me an install tutorial for linux mint cinnamon? Thank You!

**Comment by WSINTRA** [comment]
What have you tried so far?

**Comment by photographer2010** [comment]
I tried to extract it and run it. I am completely new to this type of code.

**Comment by photographer2010** [comment]
could you either make a screen recording of installation on wsl or linux mint? thanks

**Comment by WSINTRA** [comment]
The author of the software has already created a README file, so no need for the screen recording. That would take a lot of my time or anyone else's. 
Could you start by explaining, what error or problem you are having. So far we know, you have downloaded something, extracted something and then tried to run it. 
What did you download? 
What have you extracted?
What have you tried to run and more importantly what happened when you tried to run it?

**Comment by photographer2010** [comment]
I downloaded the latest release that said linux only. Then I extracted the file that is called irs from it.

**Comment by photographer2010** [comment]
I made no progress since then

**Comment by WSINTRA** [comment]
Okay well the readme goes on to say that you need to create a .yaml config file somewhere, ideally inside ~/.irs/ directory. 
That directory may not exist so using your linux terminal, try 
`$cd ~`
This should take you to your home directory. Then create the .irs folder (Having the . in front means it is a hidden folder.)
`$mkdir .irs`
Then you need to cd into that dir and create the .yaml file. 
`$cd .irs/ && touch .yaml`
Hopefully you can follow the README from there.

**Comment by WSINTRA** [comment]
If you get stuck on step 3. 
see the following https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-set-environment-variables-in-linux/

**Comment by photographer2010** [comment]
Thank You very much. I also emailed the creator of this repository directly to see if there is anything else that he can help me with.

Warmly,
David Doss
________________________________

**Comment by WSINTRA** [comment]
_I also emailed the creator of this repository directly to see if there is anything else that he can help me with._

Probably not a good idea. But hey, you are learning.

**Comment by photographer2010** [comment]
Ok, great! Thanks for the help
